# Generated by Django 5.0.2 on 2024-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_is_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to="account/", verbose_name="Add Profile Picture"
            ),
        ),
    ]
