# Generated by Django 5.0.2 on 2024-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="titles",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
