# Generated by Django 5.0.2 on 2024-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_titles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="account/",
                verbose_name="Add Profile Picture",
            ),
        ),
    ]
