# Generated by Django 5.0.2 on 2024-03-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_metatitle_alter_post_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="metaTitle",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
