# Generated by Django 5.0.2 on 2024-03-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_tag_metatitle_remove_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
