# Generated by Django 5.0.2 on 2024-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_tag_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="isPublished",
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PUBLISHED",
                max_length=9,
            ),
        ),
    ]
