# Generated by Django 5.0.2 on 2024-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_remove_post_ispublished_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="feature_image",
            field=models.ImageField(
                null=True, upload_to="blog/", verbose_name="Add Feature Image"
            ),
        ),
    ]
