# Generated by Django 5.0.2 on 2024-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="feature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/",
                verbose_name="Add Feature Image",
            ),
        ),
    ]
