# Generated by Django 5.0.2 on 2024-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_post_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
